version: 2
jobs:
    build:
        working_directory: ~/work
        machine: true
        steps:
            - checkout
            - restore_cache:
                key: docker-{{ checksum "Dockerfile" }}
                path: ~/cache/image.tar

            - run:
                command: |
                    docker load -i ~/cache/image.tar || true
                    docker history hoge
            - run: docker build -t hoge .
            - run:
                command: |
                    mkdir -p ~/cache && docker save -o ~/cache/image.tar hoge
                    docker history hoge
            - save_cache:
                key: docker-{{ checksum "Dockerfile" }}
                paths: ~/cache/image.tar
