version: 2
jobs:
    build:
        working_directory: ~/work
        machine: true
        steps:
            - checkout
            - restore_cache:
                key: docker-{{ checksum "Dockerfile" }}
                path: ~/cache/image.tar

            - run: docker load -i ~/cache/image.tar || true
            - run: docker build -t hoge .
            - run: mkdir -p ~/cache && docker save -o ~/cache/image.tar hoge
            - save_cache:
                key: docker-{{ checksum "Dockerfile" }}
                paths: ~/cache/image.tar
